"""LLM-generated factors.

Validated factor classes generated by FactorGenerator(method='llm_prompt')
will be appended to this file automatically.
"""

import pandas as pd
import numpy as np

_ = (pd, np)




class fac_volume_ratio:
    param_range = {'window': [5, 10, 20]}

    @staticmethod
    def operate(Data: pd.DataFrame, **kwargs):
        hash_tb = {chr(i): 0 for i in range(97, 123)}
        for key, value in kwargs.items():
            hash_tb[key] = value
        window = int(hash_tb['window'])

        df = Data.copy()
        avg_volume = df['volume'].rolling(window).mean()
        factor = df['volume'] / avg_volume
        return factor


class fac_price_range:
    param_range = {'window': [5, 10, 20]}

    @staticmethod
    def operate(Data: pd.DataFrame, **kwargs):
        hash_tb = {chr(i): 0 for i in range(97, 123)}
        for key, value in kwargs.items():
            hash_tb[key] = value
        window = int(hash_tb['window'])

        df = Data.copy()
        daily_range = (df['high'] - df['low']) / df['close']
        factor = daily_range.rolling(window).mean()
        return factor


class fac_close_position:
    param_range = {'window': [5, 10, 20]}

    @staticmethod
    def operate(Data: pd.DataFrame, **kwargs):
        hash_tb = {chr(i): 0 for i in range(97, 123)}
        for key, value in kwargs.items():
            hash_tb[key] = value
        window = int(hash_tb['window'])

        df = Data.copy()
        position_change = df['position'].diff()
        factor = position_change.rolling(window).mean()
        return factor


class fac_volume_price_trend:
    param_range = {'window': [5, 10, 20]}

    @staticmethod
    def operate(Data: pd.DataFrame, **kwargs):
        hash_tb = {chr(i): 0 for i in range(97, 123)}
        for key, value in kwargs.items():
            hash_tb[key] = value
        window = int(hash_tb['window'])

        df = Data.copy()
        price_change = df['close'].pct_change()
        vpt = (price_change * df['volume']).cumsum()
        factor = vpt.rolling(window).mean()
        return factor


class fac_high_low_ratio:
    param_range = {'window': [5, 10, 20]}

    @staticmethod
    def operate(Data: pd.DataFrame, **kwargs):
        hash_tb = {chr(i): 0 for i in range(97, 123)}
        for key, value in kwargs.items():
            hash_tb[key] = value
        window = int(hash_tb['window'])

        df = Data.copy()
        high_ratio = (df['high'] - df['close']) / df['close']
        low_ratio = (df['close'] - df['low']) / df['close']
        factor = (high_ratio - low_ratio).rolling(window).mean()
        return factor


class fac_atr_ratio:
    param_range = {'period': [14, 20, 26]}

    @staticmethod
    def operate(Data: pd.DataFrame, **kwargs):
        hash_tb = {chr(i): 0 for i in range(97, 123)}
        for key, value in kwargs.items():
            hash_tb[key] = value
        period = int(hash_tb['period'])

        df = Data.copy()
        high_low = df['high'] - df['low']
        high_close = (df['high'] - df['close'].shift(1)).abs()
        low_close = (df['low'] - df['close'].shift(1)).abs()
        tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
        atr = tr.rolling(period).mean()
        df['atr_ratio'] = atr / df['close']

        return df['atr_ratio']


class fac_price_volume_corr:
    param_range = {'window': [10, 20, 30]}

    @staticmethod
    def operate(Data: pd.DataFrame, **kwargs):
        hash_tb = {chr(i): 0 for i in range(97, 123)}
        for key, value in kwargs.items():
            hash_tb[key] = value
        window = int(hash_tb['window'])

        df = Data.copy()
        df['returns'] = df['close'].pct_change()
        df['volume_change'] = df['volume'].pct_change()
        df['pv_corr'] = df['returns'].rolling(window).corr(df['volume_change'])

        return df['pv_corr']


class fac_ohlc_strength:
    param_range = {'window': [5, 10, 20]}

    @staticmethod
    def operate(Data: pd.DataFrame, **kwargs):
        hash_tb = {chr(i): 0 for i in range(97, 123)}
        for key, value in kwargs.items():
            hash_tb[key] = value
        window = int(hash_tb['window'])

        df = Data.copy()
        df['close_position'] = (df['close'] - df['low']) / (df['high'] - df['low'] + 1e-8)
        df['ohlc_strength'] = df['close_position'].rolling(window).mean()

        return df['ohlc_strength']


class fac_position_change:
    param_range = {'window': [5, 10, 20]}

    @staticmethod
    def operate(Data: pd.DataFrame, **kwargs):
        hash_tb = {chr(i): 0 for i in range(97, 123)}
        for key, value in kwargs.items():
            hash_tb[key] = value
        window = int(hash_tb['window'])

        df = Data.copy()
        df['position_pct'] = df['position'].pct_change()
        df['position_sma'] = df['position_pct'].rolling(window).mean()

        return df['position_sma']
